name: arfudy_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  faker: ^2.0.0
  http: ^0.13.5
  equatable: ^2.0.5
  #  flutter_unity_widget: ^2022.2.0
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Antipasto
      fonts:
        - asset: assets/fonts/antipasto/Antipasto-Pro-Regular-trial.otf

  assets:
    - assets/images/arfudy_logo.png
