name: arfudy_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  faker: 2.1.0
  http: 1.1.0
  equatable: 2.0.5
  #  flutter_unity_widget: ^2022.2.0
  provider: 6.0.5
  get: 4.6.5
  hive: 2.2.3
  hive_flutter: 1.1.0
  dio: 5.3.2
  qr_flutter: 4.1.0
  intl: 0.18.1
  curl_logger_dio_interceptor: 1.0.0
  mobile_scanner: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Antipasto
      fonts:
        - asset: assets/fonts/antipasto/Antipasto-Pro-Regular-trial.otf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/noto/NotoSerif-Regular.ttf
        - asset: assets/fonts/noto/NotoSerif-Light.ttf
          weight: 300
        - asset: assets/fonts/noto/NotoSerif-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto/NotoSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto/NotoSerif-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/noto/NotoSerif-Black.ttf
          weight: 900

  assets:
    - assets/images/arfudy_logo.png
